baseurl = "https://rankedset.netlify.com/"
title = "Ranked Set Sampling Symposium"
theme = "hugo-universal-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

##### Sam To Do #####
# Generate table with https://www.tablesgenerator.com/markdown_tables
# Put the rest of the title on the Home page
# Reorder speakers
# Organising committee
#	Olena
#	Jennifer
#	Ray
#	Pete
# THE Biometry Hub
# BH logo on contact us
# WRI, not just University of Adelaide for Sponsors
# Logos: what and where?
#	AC21
#   University of Adelaide
#	WRI
#	School Maths, Uni of Canterbury
#	GRDC TBC
# Speakers Bio's Just TBA
# Information about what rego includes
# Rego button more obvious
# Allow booking for multiple people
# Rego open in new tab
# IE compatability
# Waite building vanishes after 3 scrolls
# New section for Abstract submission
#	Up to 20 contributing talks, maybe posters
# Update URL - rankedsetsymposium2018.website


##### Olena #####




languageCode = "en-au"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-120222240-1"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Registration"
    url  = "/registration/"
    weight = 2	

	#[[menu.registration]]
    #name = "Something"
    #url  = "/registration/"
    #weight = 2	

[[menu.main]]
    name = "Speakers"
    url  = "/speakers/"
    weight = 3
	
[[menu.main]]
    name = "Programme"
    url  = "/programme/"
    weight = 4
	
[[menu.main]]
    name = "Travel"
    url  = "/travel/"
    weight = 5
	
#[[menu.main]]
#    name = "News"
#    url  = "/post/"
#    weight = 6

[[menu.main]]
    name = "Sponsors"
    identifier = "sponsors"
    url  = "/sponsors/"
    weight = 7

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 8


[params]
    viewMorePostLink = "/post/"
    author = "The Biometry Hub"
    defaultKeywords = ["ranked set sampling", "statistics"]
    #defaultDescription = "Site template made by devcows using hugo"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

		
	
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "biometrytraining@adelaide.edu.au"

    about_us = "<p>We are a research group based at the <a href='https://www.adelaide.edu.au'>University of Adelaide</a> Waite campus. We also have a strong focus on statistical genetics research including linkage map construction, whole genome QTL analysis and genome wide association studies (GWAS). As an extension of this research we are additionally focusing on the computational aspects of digital agriculture including machine learning algorithms, high performance computing as well as user friendly online and mobile applications. </p>"
    copyright = "&copy; 2018, The Biometry Hub, University of Adelaide; All rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>The Biometry Hub</strong>
        <br>Level 2, Main Waite Building
        <br>Waite Road
        <br>Waite Campus
        <br>Urrbrae 5064
        <br>
        <strong>South Australia</strong>
      </p>
      """
	  
	# Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyAEWfK0x75ZQTAxRdqp7oNQxVSZ4FEG0gI"
  
    latitude = "-34.968035"
    longitude = "138.635613"
	direction = "Waite Building, Waite Rd, Urrbrae, SA, 5064"

[Permalinks]
    blog = "/post/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
#[params.topbar]
#    enable = false
#    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
#      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
#      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
#      </p>
#      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Invited Speakers"
    subtitle = "The speakers for this symposium"

[params.see_more]
    enable = true
#    icon = "fa fa-file-code-o"
#    title = ""
#    subtitle = ""
    link_url = "https://www.thewaite.org"
   link_text = "The Waite Campus"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Sponsors"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
